FROM openjdk:11-slim

WORKDIR /app

# Install curl (for wait-for script) and Python
RUN apt-get update && \
    apt-get install -y curl python3 python3-pip && \
    apt-get clean

# Set environment variables for Java
ENV JAVA_HOME=/usr/local/openjdk-11
ENV PATH=$JAVA_HOME/bin:$PATH

# Install Python dependencies
COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt

# Default command
CMD ["sh", "scripts/wait-for-prefect.sh"]